### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gxianlin** [teocci/OpusAndroidWrapper#1]
I find that the same file i call opusTool.writeFrame(opusBuffer, length) is smaller than encode(String wavFile, String option).The value of the second paramater of encode method is (option = "--framesize 2.5 -- comp 10 --vbr --bitrate 32").So,what' the default value of the option paramter?Thanks very much.

（在使用public native int writeFrame(ByteBuffer frame, int len)这个方法，底层使用的默认编码参数(option,即Coding Type、Bitrate、Complexity、Frame size)是什么?）

**Comment by teocci** [comment]
You can find the default values for each option here:
https://mf4.xiph.org/jenkins/view/opus/job/opus-tools/ws/man/opusenc.html
